package demo.ledger.model.dto;

public enum EventType {
    CREATE_LEDGER,
    LEDGER_CREATED,
    LEDGER_CREATION_FAILED,
    CREATE_LEDGER_ACCOUNT,
    LEDGER_ACCOUNT_CREATED,
    LEDGER_ACCOUNT_CREATION_FAILED
}
